sudo: false
language: python
python:
  - "3.5"
##Git history
git:
  depth: 3
##Addons
addons:
  apt:
    packages:
    - ghdl
##Install dependencies
install:
  - pip install -r requirements.txt
##Run tests
script: nosetests -v
notifications:
  email:
    on_success: never
    on_failure: never
