sudo: true
language: python
python:
  - "3.5"
##Git history
git:
  depth: 3
##Addons
##addons:
##  apt:
##    packages:
##    - ghdl

##Install dependencies
before_install:
  - sudo add-apt-repository ppa:pgavin/ghdl
  - sudo apt-get update
  - sudo apt-get install ghdl
install:
  - pip install -r requirements.txt
##Run tests
script: nosetests -v
notifications:
  email:
    on_success: never
    on_failure: never
