sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
##Install dependencies
install:
  - pip install -r requirements.txt
##Run tests
script: python setup.py test
notifications:
  email:
    on_success: never
    on_failure: never
