sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
##Install dependencies
install:
  - pip install -r requirements.txt
##Run tests
script: python setup.py test
notifications:
  email:
    on_success: never
    on_failure: never
